### ISSUE TITLE
Java Client failed to send Json format String to server

### ISSUE THREAD

**Issue by gaol** [vert-x3/vertx-eventbus-bridge-clients#37]
### Version

master branch

### Do you have a reproducer?

The following test fails:

```java
  @Test
  public void testSendPrimitive(final TestContext ctx) {
    final Async async = ctx.async();
    EventBusClient client = EventBusClient.tcp(baseOptions, new JacksonCodec());
    vertx.eventBus().consumer("server_addr", msg -> {
      ctx.assertEquals(new JsonObject().put("message", "hello"), msg.body());
      client.close();
      async.complete();
    });
    JsonObject jsonObject = new JsonObject().put("message", "hello");
    String json = jsonObject.encode();
    client.send("server_addr", json);  // trying to send the Json format string to server
  }
```

Client logging:
```
Sending message: {"address":"server_addr","type":"send","body":"{\"message\":\"hello\"}"} 
```

Exception:

```java
Unhandled exception 
java.lang.ClassCastException: java.lang.String cannot be cast to io.vertx.core.json.JsonObject
	at io.vertx.core.json.JsonObject.getJsonObject(JsonObject.java:253)
	at io.vertx.ext.eventbus.bridge.tcp.impl.TcpEventBusBridgeImpl.doSendOrPub(TcpEventBusBridgeImpl.java:139)
	at io.vertx.ext.eventbus.bridge.tcp.impl.TcpEventBusBridgeImpl.lambda$null$6(TcpEventBusBridgeImpl.java:277)
	at io.vertx.ext.eventbus.bridge.tcp.impl.TcpEventBusBridgeImpl.checkCallHook(TcpEventBusBridgeImpl.java:323)
	at io.vertx.ext.eventbus.bridge.tcp.impl.TcpEventBusBridgeImpl.lambda$handler$8(TcpEventBusBridgeImpl.java:268)
	at io.vertx.ext.eventbus.bridge.tcp.impl.protocol.FrameParser.handle(FrameParser.java:67)
	at io.vertx.ext.eventbus.bridge.tcp.impl.protocol.FrameParser.handle(FrameParser.java:30)
	at io.vertx.core.net.impl.NetSocketImpl$DataMessageHandler.handle(NetSocketImpl.java:379)
```

**Comment by gaol** [comment]
I am closing this as the defined format by tcp bridge requires that the body is `JsonObject`, so sending string is not supported.
